class EmployeeAlreadyExists(Exception):
    pass


class EmployeeNotFound(Exception):
    pass
